export const GROQ_API_ENDPOINT = 'https://api.groq.com'
export const GROQ_API_USER_PROFILE = '/platform/v1/user/profile'
export const GROQ_API_COMPLETIONS = '/openai/v1/chat/completions'
export const GROQ_API_MODELS = '/openai/v1/models'

export const GROQ_REFRESH_TOKEN_API = 'https://web.stytch.com/sdk/v1/sessions/authenticate'

export const GROQ_X_SDK_CLIENT = 'eyJldmVudF9pZCI6ImV2ZW50LWlkLWNkOWRiYzUzLTIzOTQtNDgxNy1hOTNlLTBkYzBiODlhNmQxNiIsImFwcF9zZXNzaW9uX2lkIjoiYXBwLXNlc3Npb24taWQtMGNmYjkxYzktZTMyNi00MDUxLWI1YzUtMDI5NjY2NjM3NDYzIiwicGVyc2lzdGVudF9pZCI6InBlcnNpc3RlbnQtaWQtYjM2MzhjNDEtMjEzNi00Yjc1LTkxOTAtNDczYTAyZWE2M2Y5IiwiY2xpZW50X3NlbnRfYXQiOiIyMDI0LTA0LTEwVDA5OjI0OjIxLjYyM1oiLCJ0aW1lem9uZSI6IkFzaWEvU2hhbmdoYWkiLCJzdHl0Y2hfdXNlcl9pZCI6InVzZXItbGl2ZS1hNjYxZGJjZS0yMWVmLTRiZGMtYjZlNC0wZDNmMGVlODhhM2YiLCJzdHl0Y2hfc2Vzc2lvbl9pZCI6InNlc3Npb24tbGl2ZS1kMzliZmZhMi03YjU2LTQ5MDctOWMwYS00N2U1MGM4N2Y5NmEiLCJhcHAiOnsiaWRlbnRpZmllciI6Imdyb3EuY29tIn0sInNkayI6eyJpZGVudGlmaWVyIjoiU3R5dGNoLmpzIEphdmFzY3JpcHQgU0RLIiwidmVyc2lvbiI6IjQuNS4zIn19'
